// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = require('marko-widgets').defineComponent({
    template: require('./template.marko'),
    init: function() {
      console.log('================');
      console.log(this.el);
      return console.log('================');
    }
  });

}).call(this);
